from pydantic import BaseModel, Field, ConfigDict, HttpUrl
from typing import List, Optional

from shared.enums.source_type import SourceType
from shared.enums.confidence_type import ConfidenceType


class NormalizerAgentInput(BaseModel):
    model_config = ConfigDict(extra='forbid')

    # --- Raw Input Fields (provided by the user, required) ---
    raw_message: str = Field(
        ...,
        description="Raw content of the note or capture, may contain noise (HTML, PDF artifacts, etc.)"
    )
    source_type: SourceType = Field(
        default=SourceType.MANUAL,
        description="Origin type of the note, used to apply the correct cleaning strategy"
    )
    source_url: Optional[HttpUrl] = Field(
        None,
        description="Source URL or file path of the original content"
    )
    raw_title: Optional[str] = Field(
        None,
        description="Title provided by the user before normalization"
    )
    raw_tags: List[str] = Field(
        default_factory=list,
        description="Tags provided by the user before normalization"
    )
    confidence_type: ConfidenceType = Field(
        default=ConfidenceType.IDEA,
        description="User's classification of the note: idea, fact or hypothesis"
    )
    confidence_level: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="User's confidence score in the information (0.0 to 1.0)"
    )

    # --- Processed Output Fields (populated by the NormalizerAgent) ---
    clean_message: Optional[str] = Field(
        None,
        description="Sanitized and standardized Markdown content, ready for chunking"
    )
    normalized_title: Optional[str] = Field(
        None,
        description="Final title: user-provided and refined, or LLM-generated if missing"
    )
    normalized_tags: List[str] = Field(
        default_factory=list,
        description="Lowercased, deduplicated and LLM-enriched tags"
    )
    detected_language: Optional[str] = Field(
        None,
        description="ISO 639-1 language code detected by the LLM (e.g. 'en', 'es')"
    )
    summary: Optional[str] = Field(
        None,
        description="Brief summary of the note generated by the LLM"
    )

    # --- Pipeline Control Fields ---
    is_normalized: bool = Field(
        default=False,
        description="Flag indicating whether the NormalizerAgent has finished processing"
    )
    normalization_errors: List[str] = Field(
        default_factory=list,
        description="List of non-fatal errors or warnings encountered during normalization"
    )
    
class LLMNormalizerOutput(BaseModel):
    clean_message: str = Field(
        description="Sanitized Markdown content, preserving semantic structure and removing noise."
    )
    normalized_title: str = Field(
        description="A concise and descriptive title for the note (max 10 words)."
    )
    normalized_tags: List[str] = Field(
        description="Standardized, lowercased, and LLM-enriched tags (including user's raw tags)."
    )
    detected_language: str = Field(
        description="ISO 639-1 language code (e.g., 'en', 'es')."
    )
    summary: str = Field(
        description="A 2-3 sentence summary explaining the core idea of the note."
    )

    # --- New Fields for CF 1 & Concept Graph ---
    key_concepts: List[str] = Field(
        default_factory=list,
        description="Identified entities, abstract ideas, or main topics for the Concept Graph."
    )
    action_items: List[str] = Field(
        default_factory=list,
        description="Extract any tasks, next steps, or implied actions from the content."
    )
    follow_up_questions: List[str] = Field(
        default_factory=list,
        description="Proposed questions to deepen the understanding or track-back this concept."
    )
    content_clarity_score: float = Field(
        ge=0.0, le=1.0,
        description="LLM score on how well-structured and clear the original content was."
    )