from pydantic import BaseModel, Field
from typing import Any, Dict, List, Optional


class SearchState(BaseModel):
    """State threaded through the hybrid search LangGraph workflow."""

    query: str = Field(..., description="Original user query.")
    expanded_queries: List[str] = Field(
        default_factory=list,
        description="Alternative phrasings generated by QueryExpansionAgent.",
    )
    query_embedding: Optional[List[float]] = Field(
        None, description="Titan v2 embedding of the original query."
    )
    bm25_results: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Rows returned by the FTS (BM25) search branch.",
    )
    vector_results: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Rows returned by the vector cosine-distance branch.",
    )
    fused_results: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Candidates after Reciprocal Rank Fusion.",
    )
    reranked_results: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Final ordered results after Cohere Rerank.",
    )
