from pydantic import BaseModel, Field
from typing import Dict, List, Optional


class ModelPricing(BaseModel):
    """Pricing details for a specific AI model."""

    input: float = Field(0.0, description="Cost per 1,000,000 (1M) input tokens (USD).")
    output: float = Field(0.0, description="Cost per 1,000,000 (1M) output tokens (USD).")


class TranscriptionSettings(BaseModel):
    """Settings for the transcription service."""

    enhancement_pipeline: List[str] = Field(default_factory=list, description="List of agents to run for enhancement.")
    auto_pause_seconds: int = Field(30, description="Automatically pause recording after this many seconds (0 = disabled).")


class SearchSettings(BaseModel):
    """Tuning knobs for the hybrid search pipeline."""

    expansion_count: int = Field(2, description="Alternative queries generated by QueryExpansionAgent.")
    top_k_before_rerank: int = Field(30, description="Candidates passed to the re-ranker.")
    rerank_top_n: int = Field(10, description="Final results returned after re-ranking.")
    language: str = Field("simple", description="PostgreSQL FTS dictionary. 'simple' is language-agnostic.")
    reranker_model: str = Field("cohere.rerank-v3-5:0", description="Bedrock model ID for Cohere Rerank.")
    rrf_k: int = Field(60, description="Rank constant k for Reciprocal Rank Fusion.")


class AppSettings(BaseModel):
    """Root configuration for non-sensitive application settings."""

    pricing: Dict[str, ModelPricing] = Field(default_factory=dict)
    active_model_id: str = Field("eu.amazon.nova-micro-v1:0", description="Currently active model ID.")
    transcription: Optional[TranscriptionSettings] = Field(default_factory=TranscriptionSettings)
    search: SearchSettings = Field(default_factory=SearchSettings)
